name: E2E tests
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        description: "AWS Access Key ID"
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: "AWS Secret Access Key"
        required: true
      AWS_REGION:
        description: "AWS Region"
        required: true
jobs:
  e2e-tests:
    env:
      REPO: ttl.sh/eks-operator-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Export tag
        id: export_tag
        run: |
          TAG=`git describe --abbrev=0 --tags 2>/dev/null || echo "v0.0.0"`
          COMMITDATE=`date -d @$(git log -n1 --format="%at") "+%FT%TZ"`
          echo "operator_tag=$TAG" >> $GITHUB_OUTPUT
          echo "commit_date=$COMMITDATE" >> $GITHUB_OUTPUT
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: |
            ${{ env.REPO }}
          tags: |
            type=sha,format=short,prefix=${{ steps.export_tag.outputs.operator_tag }}-
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.9.1
      - name: Build and push image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: eks-operator
          file: test/e2e/Dockerfile.e2e
          build-args: |
            TAG=${{ steps.export_tag.outputs.operator_tag }}
            COMMITDATE=${{ steps.export_tag.outputs.commit_date }}
            COMMIT=${{ github.sha }}
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.x
      - uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
        with:
          version: v0.23.0
          install_only: true
      - name: Create kind cluster
        run: make setup-kind
      - name: E2E tests
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: make e2e-tests
      - name: Archive artifacts
        if: always()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ci-artifacts
          path: _artifacts
          if-no-files-found: ignore

