name: Update EKS operator in rancher/rancher
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch to use for GitHub action workflow"
        required: true
        default: "main"
      rancher_ref:
        description: "Submit PR against the following rancher/rancher branch (e.g. release/v2.7)"
        required: true
        default: "release/v2.7"
      new_eks:
        description: "New EKS operator version (e.g. 1.1.0-rc2), don't include the 'v'"
        required: true
        default: ""

env:
  GOARCH: amd64
  CGO_ENABLED: 0
  SETUP_GO_VERSION: '1.21.*'

jobs:
  create-rancher-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.inputs.ref}}
          path: eks-operator
      - name: Checkout rancher/rancher
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: rancher/rancher
          ref: ${{github.event.inputs.rancher_ref}}
          path: rancher
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.SETUP_GO_VERSION }}
      - name: Run release script
        run: ./eks-operator/.github/scripts/update-rancher-dep.sh ${{github.event.inputs.new_eks}}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{secrets.CI_BOT_TOKEN}}
          push-to-fork: highlander-ci-bot/rancher
          title: ' Update EKS operator to v${{github.event.inputs.new_eks}}'
          body: |
            Update EKS operator to v${{github.event.inputs.new_eks}}

            Changelog: https://github.com/rancher/eks-operator/releases/tag/v${{github.event.inputs.new_eks}}

            cc @rancher/highlander
          branch-suffix: timestamp
          base: ${{github.event.inputs.rancher_ref}}
          path: ./rancher/
